<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQy6xbad\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQy6xbad/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerQy6xbad.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerQy6xbad\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerQy6xbad\appProdProjectContainer([
    'container.build_hash' => 'Qy6xbad',
    'container.build_id' => '12d96195',
    'container.build_time' => 1700103484,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQy6xbad');
